### ISSUE TITLE
Desambiguación de ServiceProvider

### ISSUE THREAD

**Issue by iformas** [freshworkstudio/ChileanBundle#1]
Al menos, en laravel 5.2, en mi caso fue necesario agregar en
ChileanBundleServiceProvider.php
la linea 
`use Illuminate\Support\ServiceProvider;`
para evitar el error

> Class 'Freshwork\ChileanBundle\Laravel\ServiceProvider' not found

**Comment by gdespirito** [comment]
Yo diría que si tiene esa línea: https://github.com/freshworkstudio/ChileanBundle/blob/master/src/Laravel/ChileanBundleServiceProvider.php

¿Que versión estás ocupando?
