### ISSUE TITLE
Rut 72041-0

### ISSUE THREAD

**Issue by JGamboa** [freshworkstudio/ChileanBundle#11]
Lo detecta como invalido, pero es una persona que existe y esta viva aunque no lo crean.

![imagen](https://user-images.githubusercontent.com/4482664/50673289-8ec3ac00-0fbb-11e9-9bef-1f964719ab11.png)

**Comment by gdespirito** [comment]
jaja, no tenía idea. Pensé que era imposible. De todas formas, acabo de subir una nueva versión que tiene un método para cambiar el número mínimo de caracteres que se requiere para que lo tome como un RUT válido. 

```php
$rut = Rut::parse('73041-0')->minChars(1)->validate();
```

**Comment by JGamboa** [comment]
De hecho como dato curioso, la ultima vez que ese rut timbro facturas fue el año pasado xD
