### ISSUE TITLE
Bug on short example RUT

### ISSUE THREAD

**Issue by roro66** [freshworkstudio/ChileanBundle#2]
If you enter a short example RUT i.e. 1-9, 2-7 or 3-5 it returns  INVALID FORMAT.

Si ingresas un rut corto de ejemplo  1-9, 2-7 o 3-5 devuelve formato invalido.

**Comment by gdespirito** [comment]
De hecho, está pensado para funcionar así. Son ruts que de seguro son
falsos y no existen.

**Comment by roro66** [comment]
Ok.

Aprovecho de agradecerte el aporte.
Tu programa no solo es funcional sino que , ademas, esta bien hecho y el codigo es muy facil de leer y entender. (bonito).

Buen trabajo. Gracias.

⁣Enviado desde TypeApp ​
