### ISSUE TITLE
Validation con Laravel

### ISSUE THREAD

**Issue by javierpacareu** [freshworkstudio/ChileanBundle#4]
Hola:
No se si será por cómo lo hice yo pero al poner:
`$validator = Validator::make(Request::all(),			
			[
			'rut' => 'required| cl_rut'
			]
		);`
Se debe asignar el atributo `cl_rut` en `validation.php` algo así como:
`'cl_rut'               => 'El :attribute no es válido.', // El rut no es válido`

A lo mejor es algo que estoy haciendo mal yo, pero bueno cuando lo puse me funcionó. De no ponerlo lo que se muestra al usuario en caso de invalidez es `validation.cl_rut`, es decir que como que faltaba definirlo. 
Y al no verlo en la explicación en el **github** pues me pareció oportuno mencionarlo

Saludos desde Chile 👍

**Comment by gdespirito** [comment]
Gracias por el dato, efectivamente hay que definir el mensaje manualmente. Acabo de aceptar un Pull Request de @eaguad1337 que arregla esto y pone un mensaje por defecto. Saludos!
