### ISSUE TITLE
validacion rut

### ISSUE THREAD

**Issue by cocuba** [freshworkstudio/ChileanBundle#8]
Hola, estoy utilizando la validación del rut (`cl_rut`) cuando ingreso cualquier numero, retorna el mensaje en la vista diciendo " Debe ser un rut válido " pero cuando mando el campo del rut vacío salta la `InvalidFormatException`, en ese mismo campo tengo la validación de requerido pero me salta es la excepción

**Comment by cocuba** [comment]
ya resolvi, mi error... gracias por este paquete me ayuda en todos los proyectos, saludos

**Comment by gdespirito** [comment]
Hola César,

¿Era problema del paquete? ¿Recomiendas hacerle algun cambio?

Saludos!


GONZALO DE-SPIRITO ZÚÑIGA | Web Development
*FRESHWORK STUDIO CHILE*


Fijo: 02 - 2979 0059| Móvil: 881 53 776 |  gonzalo@freshworkstudio.com
<gonzalo@freshworkstudio.com>

Cuida el medio ambiente. No imprimas este e-mail a menos que sea necesario.

2018-01-25 10:30 GMT-03:00 Cesar Augusto Vallenilla <
notifications@github.com>:
