### ISSUE TITLE
Excepción no controlada en formateo del mensaje

### ISSUE THREAD

**Issue by cristianponce** [freshworkstudio/ChileanBundle#9]
Tengo un desarrollo en CentOS 7.1, con PHP 7.1.14 y Laravel 5.3 como base. He generado un formulario que utiliza el plugin _proengsoft/laravel-jsvalidation_ e implementando una validación mediante Request. 

En la declaración del Request tengo las reglas declaradas de la siguiente forma:

```
public function rules()
    {
        return [
            'rut'                   => 'cl_rut',
            'name'                  => 'min:3|max:150',
            'lastname'              => 'min:3|max:150',
            'mother_lastname'       => 'min:3|max:150',
            'email'                 => 'email',
            'g-recaptcha-response'  => 'required|captcha'
        ];
    }
```

Y la excepción que obtengo es:

```

FatalErrorException in dc00551a842fcd1e25112dcceb1b6d5d76b072da.php line 0:
Method Proengsoft\JsValidation\Javascript\JavascriptValidator::__toString() must not throw an exception, caught ErrorException: ErrorException: Undefined offset: 0 in /var/www/website.test/vendor/freshwork/chilean-bundle/src/Laravel/ChileanBundleServiceProvider.php:41
Stack trace:
#0 /var/www/website.test/vendor/freshwork/chilean-bundle/src/Laravel/ChileanBundleServiceProvider.php(41): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined offse...', '/internet/VDoma...', 41, Array)
#1 [internal function]: Freshwork\ChileanBundle\Laravel\ChileanBundleServiceProvider->Freshwork\ChileanBundle\Laravel\{closure}('validation.cl_r...', 'rut', 'cl_rut', Array)
#2 /var/www/website.test/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(3311): call_user_func_array(Object(Closure), Array)
#3 /var/www/website.test/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(2191): Illuminate
```

He rastreado el error hasta esta linea en el archivo "_ChileanBundleServiceProvider.php_":

```
Validator::replacer('cl_rut', function ($message, $attribute, $rule, $parameters) {
    return str_replace('El atributo :attribute es inválido', $parameters[0], $message);
});
```
Y al parecer el array "$attribute" viene vacío. Pero entiendo que eso no tendría que afectar dado que existe un mensaje por defecto.

He intentado creando / eliminando la declaración del mensaje custom en el archivo "resources/lang/xx/validation.php" tanto en el lenguaje principal como en el default y asi todo el error persiste.

Lo otro que encontré es que si descargo la versión con composer obtengo la 2.0.11 pero contrario a la ultima versión en github esta sigue teniendo la declaración que pegue mas arriba.

Espero puedan ayudarme.

**Comment by diruzcode** [comment]
@gonzunigad  actualiza la version en composer ya que la version de codigo fuente que esta descargando composer es la version de tu ultimo release  2.0.9 y no la 2.0.11 donde corregiste con el ultimo Fix 

Saludos

**Comment by gdespirito** [comment]
Acabo de subir lo último y dejé la versión como 2.1.1

**Comment by cristianponce** [comment]
Ahi quedo funcionando OK. Gracias!

**Comment by JGamboa** [comment]
esto se maneja como exception finalmente y no como validación?

**Comment by gdespirito** [comment]
Como validación.
